name: Weekly Digest

on:
  schedule:
    - cron: '0 15 * * 2'  # Every Tuesday at 8am MST (15:00 UTC)
  workflow_dispatch:      # Manual trigger

jobs:
  run-digest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]  # or your requirements.txt

      - name: Run digest CLI
        env:
          LEAGUE_ID: ${{ secrets.LEAGUE_ID }}
        run: |
          python -m fantasy_ai.cli digest --week $(date +%U)