name: Strategy Digest

on:
  schedule:
    - cron: '0 15 * * 2'  # Every Tuesday at 8am MST (15:00 UTC)
  workflow_dispatch:

jobs:
  run-strategy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install requests python-dotenv

      - name: Run Strategy Digest
        env:
          PYTHONPATH: ${{ github.workspace }}/src
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          SEND_FROM: ${{ secrets.SEND_FROM }}
          LEAGUE_ID: ${{ secrets.LEAGUE_ID }}
          SLEEPER_DISPLAY_NAME: ${{ secrets.SLEEPER_DISPLAY_NAME }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python src/fantasy_ai/cli.py strategy